<?php

namespace Database\Seeders;

use App\Models\Embassy;
use Illuminate\Database\Seeder;

class EmbassySeeder extends Seeder
{
    public function run(): void
    {
        Embassy::truncate();

        $embassies = [
            [
                'country_name_ar' => 'اسبانيا',
                'country_name_en' => 'Spain',
                'slug' => 'spain',
                'flag_emoji' => '🇪🇸',
                'appointment_status' => 'open',
                'next_close_date' => '2026-04-20',
                'appointment_price' => 4000,
                'price_currency' => 'EGP',
                'sort_order' => 1,
            ],
            [
                'country_name_ar' => 'المانيا',
                'country_name_en' => 'Germany',
                'slug' => 'germany',
                'flag_emoji' => '🇩🇪',
                'appointment_status' => 'open',
                'next_close_date' => '2026-04-10',
                'appointment_price' => 3500,
                'price_currency' => 'EGP',
                'sort_order' => 2,
            ],
            [
                'country_name_ar' => 'ايطاليا',
                'country_name_en' => 'Italy',
                'slug' => 'italy',
                'flag_emoji' => '🇮🇹',
                'appointment_status' => 'open',
                'next_close_date' => '2026-04-25',
                'appointment_price' => 6500,
                'price_currency' => 'EGP',
                'sort_order' => 3,
            ],
            [
                'country_name_ar' => 'هولندا',
                'country_name_en' => 'Netherlands',
                'slug' => 'netherlands',
                'flag_emoji' => '🇳🇱',
                'appointment_status' => 'open',
                'next_close_date' => '2026-04-10',
                'appointment_price' => 3200,
                'price_currency' => 'EGP',
                'sort_order' => 4,
            ],
            [
                'country_name_ar' => 'امريكا',
                'country_name_en' => 'United States',
                'slug' => 'usa',
                'flag_emoji' => '🇺🇸',
                'appointment_status' => 'open',
                'next_close_date' => '2026-05-10',
                'appointment_price' => 6500,
                'price_currency' => 'EGP',
                'notes_ar' => 'مواعيد السفارة الأمريكية متاحة. يرجى ملء نموذج DS-160 قبل الحجز.',
                'notes_en' => 'US Embassy appointments available. Please complete DS-160 form before booking.',
                'sort_order' => 5,
            ],
            [
                'country_name_ar' => 'انجلترا',
                'country_name_en' => 'United Kingdom',
                'slug' => 'uk',
                'flag_emoji' => '🇬🇧',
                'appointment_status' => 'open',
                'next_close_date' => '2026-04-10',
                'appointment_price' => 6500,
                'price_currency' => 'EGP',
                'sort_order' => 6,
            ],
            [
                'country_name_ar' => 'قبرص',
                'country_name_en' => 'Cyprus',
                'slug' => 'cyprus',
                'flag_emoji' => '🇨🇾',
                'appointment_status' => 'open',
                'next_close_date' => '2026-04-18',
                'appointment_price' => 2800,
                'price_currency' => 'EGP',
                'notes_ar' => 'الحجز مفتوح ومواعيد متاحة خلال أسبوع.',
                'notes_en' => 'Booking open with appointments available within a week.',
                'sort_order' => 7,
            ],
            [
                'country_name_ar' => 'اليونان',
                'country_name_en' => 'Greece',
                'slug' => 'greece',
                'flag_emoji' => '🇬🇷',
                'appointment_status' => 'open',
                'next_close_date' => '2026-04-10',
                'appointment_price' => 2500,
                'price_currency' => 'EGP',
                'sort_order' => 8,
            ],
            [
                'country_name_ar' => 'البرتغال',
                'country_name_en' => 'Portugal',
                'slug' => 'portugal',
                'flag_emoji' => '🇵🇹',
                'appointment_status' => 'open',
                'next_close_date' => '2026-04-10',
                'appointment_price' => 3500,
                'price_currency' => 'EGP',
                'sort_order' => 9,
            ],
            [
                'country_name_ar' => 'المجر',
                'country_name_en' => 'Hungary',
                'slug' => 'hungary',
                'flag_emoji' => '🇭🇺',
                'appointment_status' => 'open',
                'next_close_date' => '2026-04-30',
                'appointment_price' => 2500,
                'price_currency' => 'EGP',
                'notes_ar' => 'مواعيد متاحة. أسعار مخفضة للمجموعات.',
                'notes_en' => 'Appointments available. Group discounts offered.',
                'sort_order' => 10,
            ],
            [
                'country_name_ar' => 'البرازيل',
                'country_name_en' => 'Brazil',
                'slug' => 'brazil',
                'flag_emoji' => '🇧🇷',
                'appointment_status' => 'open',
                'next_close_date' => '2026-04-10',
                'appointment_price' => 6500,
                'price_currency' => 'EGP',
                'sort_order' => 11,
            ],
            [
                'country_name_ar' => 'فرنسا',
                'country_name_en' => 'France',
                'slug' => 'france',
                'flag_emoji' => '🇫🇷',
                'appointment_status' => 'open',
                'next_close_date' => '2026-04-12',
                'appointment_price' => 3200,
                'price_currency' => 'EGP',
                'notes_ar' => 'المواعيد محدودة. يرجى الحجز فوراً. يُطلب حجز فندقي مؤكد.',
                'notes_en' => 'Limited slots available. Book immediately. Confirmed hotel reservation required.',
                'sort_order' => 12,
            ],
            [
                'country_name_ar' => 'كرواتيا',
                'country_name_en' => 'Croatia',
                'slug' => 'croatia',
                'flag_emoji' => '🇭🇷',
                'appointment_status' => 'open',
                'next_close_date' => '2026-04-10',
                'appointment_price' => 3500,
                'price_currency' => 'EGP',
                'sort_order' => 13,
            ],
            [
                'country_name_ar' => 'التشيك',
                'country_name_en' => 'Czech Republic',
                'slug' => 'czech-republic',
                'flag_emoji' => '🇨🇿',
                'appointment_status' => 'open',
                'next_close_date' => '2026-04-10',
                'appointment_price' => 3500,
                'price_currency' => 'EGP',
                'notes_ar' => 'يُرجى تجهيز تأمين سفر ساري.',
                'notes_en' => 'Please prepare valid travel insurance.',
                'sort_order' => 14,
            ],
            [
                'country_name_ar' => 'بولندا',
                'country_name_en' => 'Poland',
                'slug' => 'poland',
                'flag_emoji' => '🇵🇱',
                'appointment_status' => 'open',
                'next_close_date' => '2026-04-10',
                'appointment_price' => 3500,
                'price_currency' => 'EGP',
                'notes_ar' => 'الحجز متاح. مطلوب خطاب دعوة للتأشيرة السياحية.',
                'notes_en' => 'Booking available. Invitation letter required for tourist visa.',
                'sort_order' => 15,
            ],
        ];

        foreach ($embassies as $data) {
            Embassy::create(array_merge($data, ['is_active' => true]));
        }
    }
}
